compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistries:
  "https://registry.npmjs.org":
    npmAuthToken: "${NODE_AUTH_TOKEN:-}"

packageExtensions:
  uniforms-bridge-simple-schema-2@*:
    dependencies:
      react: ^18.2.0

yarnPath: .yarn/releases/yarn-4.10.0.cjs
